// routes/photos/china.tsx
import { join } from "$std/path/join.ts";
import ImageCollection from "@/islands/ImageCollection.tsx";

const baseImagePath = join("img", "photos", "china");

export default async function China() {
	const files = (await Array.fromAsync(
		Deno.readDir(join(Deno.cwd(), "static", baseImagePath)),
	)).map((f) => f.name).toSorted();

	return (
		<ImageCollection
			country={{
				name: "China",
				mask: "/img/photos/mask.png",
				sky: "/img/photos/sky.jpg",
			}}
			cities={[
				{
					images: files.map((f) => `/${baseImagePath}/${f}`),
				},
			]}
		/>
	);
}

// src/routes/(reset)/photos/china/+page.svelte
<script lang="ts">
	import ImageCollection from "$lib/components/ImageCollection.svelte";
</script>

<ImageCollection
	country={{
		name: "China",
		mask: "/img/photos/china/mask.png",
		sky: "/img/photos/china/sky.jpg",
	}}
	cities={[
		{
			name: "西安",
			english: "Xi'an",
			images: [
				"https://source.unsplash.com/random/1",
				"https://source.unsplash.com/random/2",
				"https://source.unsplash.com/random/3",
				"https://source.unsplash.com/random/4",
				"https://source.unsplash.com/random/5",
			],
		},
	]}
>
	<div>
		<h2>Sources</h2>
		<a href="https://eliasruiz.com/china">Elias Ruiz</a>
	</div>
</ImageCollection>

<style>
	/* Overwrite */
	:global(.hero-title) {
		font-size: 20vw;
		bottom: 10%;
	}
</style>
