// src/lib/components/ImageCollection.svelte
<script lang="ts">
  import Gallery from "$lib/components/Gallery.svelte";

  export let country: {
    name: string;
    mask: string;
    sky: string;
  };

  export let cities: {
    name?: string;
    english?: string;
    images: string[];
  }[];

  let parallaxTitle: HTMLDivElement;

  function onScroll() {
    parallaxTitle.style.top = window.scrollY * -0.9 + "px";
  }
</script>

<svelte:window on:scroll={onScroll} />

<div class="hero">
  <div
    class="hero-img hero-img-mask"
    style="background-image: url('{country.mask}')"
  />
  <div class="parallax-title" bind:this={parallaxTitle}>
    <h1 class="hero-title">{country.name}</h1>
  </div>
  <div class="hero-img" style="background-image: url('{country.sky}');" />
</div>

{#each cities as city}
  <div class="city">
    {#if city.name}
      <h2>{city.name}</h2>
    {/if}
    {#if city.english}
      <p>{city.english}</p>
    {/if}
    <Gallery>
      {#each city.images as src}
        <img {src} alt="" />
      {/each}
    </Gallery>
  </div>
{/each}

<div class="city">
  <slot />
</div>

<style>
  .hero {
    position: relative;
    height: 100vh;
  }

  .hero-img {
    background-repeat: no-repeat;
    background-size: cover;
    position: absolute;
    bottom: 0;
    height: 100%;
    width: 100%;
  }

  .hero-img-mask {
    z-index: 3;
    background-size: 100%;
    background-position: bottom;
  }

  .parallax-title {
    font-family: var(--mono);
    position: absolute;
    height: 100vh;
    width: calc(100% - 5vw);
    padding-left: 5vw;
  }

  .hero-title {
    z-index: 2;
    margin: 0;
    position: absolute;
    color: white;
    text-transform: uppercase;
    font-weight: bold;
    font-size: 20vw;
    bottom: 10%;
  }

  @media screen and (max-width: 768px) {
    .hero-img-mask {
      background-size: 300%;
      background-position: 85% 100%;
    }

    .parallax-title {
      display: grid;
      place-items: center;
      width: 100%;
      padding-left: 0;
    }

    .hero-title {
      bottom: 50%;
      font-size: 20vw;
    }
  }

  div.city {
    margin-top: 100px;
    max-width: 980px;
    margin: 0 auto;
  }

  @media (max-width: 768px) {
    div.city {
      padding: 0 1em;
    }
  }
</style>

// islands/ImageCollection.tsx
import { useEffect } from "preact/hooks";
import { ButtonLink } from "@/components/utils.tsx";
import Gallery from "@/islands/Gallery.tsx";

type ImageCollectionProps = {
	country: {
		name: string;
		mask: string;
		sky: string;
	};
	cities: Array<{
		name?: string;
		english?: string;
		images: string[];
	}>;
};

export default function ImageCollection(props: ImageCollectionProps) {
	const { country } = props;

	function handleScroll() {
		// @ts-expect-error - This is defined lol
		globalThis.parallaxTitle.style.top = globalThis.scrollY * -0.9 + "px";
	}

	useEffect(() => {
		globalThis.addEventListener("scroll", handleScroll);
	}, []);

	return (
		<>
			<div class="relative h-screen">
				<div
					class="absolute bg-no-repeat bottom-0 h-full w-full bg-pos-85-100 bg-size-300 md:bg-bottom md:bg-size-100"
					style={{
						backgroundImage: `url('${country.mask}')`,
						zIndex: 3,
					}}
				/>
				<div
					id="parallaxTitle"
					class="absolute font-mono h-screen grid place-items-center w-full md:block md:w-auto"
					style={{ width: "calc(100% - 5vw)", paddingLeft: "5vw" }}
				>
					<h1
						class="absolute m-0 text-white uppercase font-bold bottom-[30%] md:bottom-[10%]"
						style={{
							zIndex: 2,
							fontSize: "20vw",
							"view-transition-name": `photos-${country.name.toLowerCase()}`,
						}}
					>
						{country.name}
					</h1>
				</div>
				<div
					class="absolute bg-no-repeat bg-bottom bottom-0 h-full w-full bg-cover"
					style={{
						backgroundImage: `url('${country.sky}')`,
					}}
				/>
			</div>

			<div class="mx-auto px-2.5 md:px-0 md:max-w-screen-sm lg:max-w-screen-md xl:max-w-screen-lg">
				<p class="mt-2.5">
					<ButtonLink name="&larr; Back to home page" href="/#photos" />
				</p>
				{props.cities.map((city) => (
					<div class="mt-2.5">
						{city.name && (
							<h2 class="text-3xl mb-2 font-bold tracking-tight">
								{city.name}
							</h2>
						)}
						{city.english && <p>{city.english}</p>}
						<Gallery images={city.images} />
					</div>
				))}
			</div>
		</>
	);
}
