// src/routes/content/projects/tanuki/support/+page.svelte
<script lang="ts">
	let title: string, msg: string;

	async function sendSupport() {
		open(
			"mailto:contact-project+felix-schindler-gitlab-ios-33025310-issue-@incoming.gitlab.com" +
				"?subject=" +
				encodeURIComponent(title) +
				"&body=" +
				encodeURIComponent(msg)
		);
	}
</script>

<h2>Support</h2>

<form class="card" on:submit|preventDefault={sendSupport}>
	<h3>Support request</h3>
	<input placeholder="Title" type="text" bind:value={title} />
	<textarea placeholder="Message" cols="30" rows="10" bind:value={msg} />
	<button type="submit" disabled={!title || !msg}>Send</button>
</form>

<h3 id="faq">FAQ</h3>
<div class="grid">
	<div class="card">
		<h3>Why does the app cost anything?</h3>
		<p>
			Apple charges money for developer accounts, which you need to be able to deploy apps to the
			App Store. <small>Also, I shouldn't work for free forever.</small>
		</p>
		<p>I'm not a fan of monthly subscriptions, so that's why there's just the one-time-cost.</p>
	</div>
	<div class="card">
		<h3>How to submit a feature request?</h3>
		<p>
			Just fill in the form above and send the email, or head over to <a
				href="https://gitlab.com/felix-schindler/gitlab-ios">the repo</a
			>
			and open an issue yourself.
		</p>
		<p>You can also just open a merge request if you'd like!</p>
	</div>
	<div class="card">
		<h3>When will the app be feature complete?</h3>
		<p>Feature completeness is a hard thing to achive as GitLab is a pretty big software.</p>
		<p>
			The goal for the beginning is to support the most used features by most users. After that, the
			focus is on whatever the users suggest. When there are no suggestions the app will receivice
			incremental updates with no specific focus.
		</p>
	</div>
</div>

// routes/projects/tanuki/support.tsx
const questions = [
	{
		title: "Why does the app cost anything?",
		answers: [
			"Apple charges money for developer accounts, which you need to be able to deploy apps to the App Store. Also, I shouldn't work for free forever.",
			"I'm not a fan of monthly subscriptions, so that's why there's just the one-time-cost.",
		],
	},
	{
		title: "How to submit a feature request?",
		answers: [
			"Just fill in the form above and send the email, or head over to the repo and open an issue yourself.",
			"You can also just open a merge request if you'd like!",
		],
	},
	{
		title: "When will the app be feature complete?",
		answers: [
			"Feature completeness is a hard thing to achive as GitLab is a pretty big software.",
			"The goal for the beginning is to support the most used features by most users. After that, the focus is on whatever the users suggest. When there are no suggestions the app will receivice incremental updates with no specific focus.",
		],
	},
] as const;

export default function TanukiSupport() {
	return (
		<div class="flex flex-col gap-5">
			<div>
				<h2 class="text-3xl mb-2 font-bold tracking-tight">Support</h2>
				<form
					class="flex flex-col gap-2 items-end"
					action="mailto:contact-project+felix-schindler-gitlab-ios-33025310-issue-@incoming.gitlab.com"
					method="get"
				>
					<input
						type="text"
						name="subject"
						class="block text-base w-full py-1 px-2 rounded-md"
						placeholder="Subject"
					/>
					<textarea
						name="body"
						rows={5}
						class="block text-base w-full py-1 px-2 rounded-md"
						placeholder="Message"
					>
					</textarea>
					<button
						class="py-1 px-2 rounded-md bg-black text-white transition-transform hover:scale-90 dark:bg-white dark:text-black"
						type="submit"
					>
						&rarr; Send
					</button>
				</form>
			</div>
			<div>
				<h2 id="faq" class="text-3xl mb-2 font-bold tracking-tight">FAQ</h2>
				<div className="grid grid-cols-default gap-2">
					{questions.map((question) => (
						<div class="py-1 px-2 rounded-md bg-gray-200 dark:bg-gray-800">
							<h3 class="text-xl font-bold mb-2">{question.title}</h3>
							{question.answers.map((answer) => <p class="mb-1">{answer}</p>)}
						</div>
					))}
				</div>
			</div>
		</div>
	);
}
