// routes/photos/china.tsx
import { join } from "$std/path/join.ts";
import ImageCollection from "@/islands/ImageCollection.tsx";

const baseImagePath = join("img", "photos", "china");

export default async function China() {
	const files = (await Array.fromAsync(
		Deno.readDir(join(Deno.cwd(), "static", baseImagePath)),
	)).map((f) => f.name).toSorted();

	return (
		<ImageCollection
			country={{
				name: "China",
				mask: "/img/photos/mask.png",
				sky: "/img/photos/sky.jpg",
			}}
			cities={[
				{
					images: files.map((f) => `/${baseImagePath}/${f}`),
				},
			]}
		/>
	);
}

// src/routes/content/photos/china/+page.svelte
<script lang="ts">
	import ImageCollection from "$lib/components/ImageCollection.svelte";
	import type { PageData } from "./$types";

	export let data: PageData;
	const baseImagePath = "/img/photos/china";
</script>

<ImageCollection
	country={{
		name: "China",
		mask: "/img/photos/mask.png",
		sky: "/img/photos/sky.jpg",
	}}
	cities={[
		{
			images: data.files.map((f) => `${baseImagePath}/${f}`),
		},
	]}
/>

<style>
	/* Overwrite */
	:global(.hero-title) {
		font-size: 20vw;
		bottom: 10%;
	}
</style>
